# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_branch]
symbol = '🌱 '
format = 'on $symbol[\[$branch\]]($style) '

[git_status]
disabled = true

[python]
python_binary = 'python3'
